name: nmfp
channels:
  - conda-forge
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cuda-nvcc=12.4.131
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.5.0
  - pandas=2.1.4
  - pip=25.0
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - essentia==2.1b6.dev1110
      - flatbuffers==25.2.10
      - gast==0.4.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - idna==3.10
      - keras==2.13.1
      - libclang==18.1.1
      - markdown==3.8
      - markupsafe==3.0.2
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - packaging==24.2
      - protobuf==4.25.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - soundfile==0.13.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - typing-extensions==4.5.0
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
